//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.MaterialManager.Contracts.Processing.Optimization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BookHeightModeDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookHeightModeDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.MaterialManager.Contracts.Processing.Optimization.BookHeightModeDisp" +
                            "layNames", typeof(BookHeightModeDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begrenzte Pakethöhe.
        /// </summary>
        internal static string LimitedBookHeight {
            get {
                return ResourceManager.GetString("LimitedBookHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Pakethöhe der Maschine.
        /// </summary>
        internal static string MaximumBookHeightOfMachine {
            get {
                return ResourceManager.GetString("MaximumBookHeightOfMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximaler Sägeblattüberstand.
        /// </summary>
        internal static string MaximumSawBladeProjectionDeduction {
            get {
                return ResourceManager.GetString("MaximumSawBladeProjectionDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelplatte.
        /// </summary>
        internal static string SingleBoard {
            get {
                return ResourceManager.GetString("SingleBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spezifischer Wert.
        /// </summary>
        internal static string SpecificValue {
            get {
                return ResourceManager.GetString("SpecificValue", resourceCulture);
            }
        }
    }
}
