//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.ProductionManager.Contracts.ProductionItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductionItemFeedbackActionDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductionItemFeedbackActionDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.ProductionManager.Contracts.ProductionItems.ProductionItemFeedbackAc" +
                            "tionDisplayNames", typeof(ProductionItemFeedbackActionDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossen.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bauteil zugeschnitten.
        /// </summary>
        public static string DividingPartConfirmed {
            get {
                return ResourceManager.GetString("DividingPartConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bestätigt.
        /// </summary>
        public static string FeedbackConfirmed {
            get {
                return ResourceManager.GetString("FeedbackConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bestätigt durch {0}.
        /// </summary>
        public static string FeedbackConfirmedByParent {
            get {
                return ResourceManager.GetString("FeedbackConfirmedByParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In Produktion.
        /// </summary>
        public static string InProduction {
            get {
                return ResourceManager.GetString("InProduction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Etikett gedruckt.
        /// </summary>
        public static string Labeled {
            get {
                return ResourceManager.GetString("Labeled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bauteil ausgelagert.
        /// </summary>
        public static string PickedFromSortingShelf {
            get {
                return ResourceManager.GetString("PickedFromSortingShelf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bauteil einsortiert.
        /// </summary>
        public static string PlacedInSortingShelf {
            get {
                return ResourceManager.GetString("PlacedInSortingShelf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Produktionsbereit.
        /// </summary>
        public static string ReadyForProduction {
            get {
                return ResourceManager.GetString("ReadyForProduction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empfangen von productionManager.
        /// </summary>
        public static string ReceivedByProductionManager {
            get {
                return ResourceManager.GetString("ReceivedByProductionManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gesendet an intelliDivide.
        /// </summary>
        public static string SentToIntelliDivide {
            get {
                return ResourceManager.GetString("SentToIntelliDivide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gesendet an productionAssist.
        /// </summary>
        public static string SentToProductionAssist {
            get {
                return ResourceManager.GetString("SentToProductionAssist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Aktion.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
