table HistoricalData
	lineageTag: a1c61859-8e53-4466-ab03-f9f5cf1a8052

	column startTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 6625052c-5ec9-461a-b59f-654881d2b2dc
		summarizeBy: none
		sourceColumn: startTime

		variation Variation
			isDefault
			relationship: df988ed5-6973-4590-ad43-24a7c580973a
			defaultHierarchy: LocalDateTable_d1c2c3de-2674-481f-81ba-ba60fcadfa2a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column endTime
		dataType: dateTime
		formatString: General Date
		lineageTag: d1aa39bc-fd36-457c-952b-981717264fd4
		summarizeBy: none
		sourceColumn: endTime

		variation Variation
			isDefault
			relationship: f8df9e2f-2bba-4d85-a122-48b921c2a017
			defaultHierarchy: LocalDateTable_c8831bc6-be9f-4a89-9d07-dcaa1b03f3dc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column instanceId
		dataType: string
		lineageTag: 598fa8ed-283a-431a-9c78-bcb13f08b5ba
		summarizeBy: none
		sourceColumn: instanceId

		annotation SummarizationSetBy = Automatic

	column machineNumber
		dataType: string
		lineageTag: fc2609bb-c355-486b-a1ba-6ea5a2931c6c
		summarizeBy: none
		sourceColumn: machineNumber

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: int64
		formatString: 0
		lineageTag: b859dfad-8d4f-4f22-80e4-331bec53cf1a
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = User

	column 'localizedSource.'
		dataType: string
		lineageTag: b41e3cf5-7639-464c-af65-6293e42287f0
		summarizeBy: none
		sourceColumn: localizedSource.

		annotation SummarizationSetBy = Automatic

	column de-DE
		dataType: string
		lineageTag: 76761bd0-32e2-440b-a175-f5494dc3efc9
		summarizeBy: none
		sourceColumn: de-DE

		annotation SummarizationSetBy = Automatic

	column en-US
		dataType: string
		lineageTag: 5e8c0de3-0ca9-4206-b251-40903a2169b1
		summarizeBy: none
		sourceColumn: en-US

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: ced8bba8-61e4-45b8-b1e8-3b00ca48b076
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column sourceClass
		dataType: string
		lineageTag: f87b4f49-8f09-4fa3-90bc-556e063c59b6
		summarizeBy: none
		sourceColumn: sourceClass

		annotation SummarizationSetBy = Automatic

	column sourceInstance
		dataType: string
		lineageTag: f6962cbd-1423-497e-b512-5eca5a2419c3
		summarizeBy: none
		sourceColumn: sourceInstance

		annotation SummarizationSetBy = Automatic

	column sourceMessageId
		dataType: int64
		formatString: 0
		lineageTag: d5d60b2f-f88e-4d49-96a0-6885359ef26b
		summarizeBy: none
		sourceColumn: sourceMessageId

		annotation SummarizationSetBy = User

	column causality
		dataType: string
		lineageTag: a57931ba-fcd6-4d06-89eb-267586e4af81
		summarizeBy: none
		sourceColumn: causality

		annotation SummarizationSetBy = Automatic

	partition HistoricalData-b586845e-fdce-4813-ad72-829186fbf2e0 = m
		mode: import
		source =
				let
				    RawDocument = Web.Contents(Text.Combine( {"https://connect.homag.cloud/api/mmr-mobile/machinedata/machines/hgt200695809/alerts/history?daysBack=5"})),
				    #"Imported JSON" = Json.Document(RawDocument,65001),
				    #"Converted to Table" = Table.FromList(#"Imported JSON", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"startTime", "endTime", "instanceId", "machineNumber", "severity", "localizedSource", "localizedMessage", "category", "sourceClass", "sourceInstance", "sourceMessageId", "causality"}, {"startTime", "endTime", "instanceId", "machineNumber", "severity", "localizedSource", "localizedMessage", "category", "sourceClass", "sourceInstance", "sourceMessageId", "causality"}),
				    #"Expanded localizedSource" = Table.ExpandRecordColumn(#"Expanded Column1", "localizedSource", {""}, {"localizedSource."}),
				    #"Expanded localizedMessage" = Table.ExpandRecordColumn(#"Expanded localizedSource", "localizedMessage", {"de-DE", "en-US"}, {"de-DE", "en-US"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded localizedMessage",{{"startTime", type datetimezone}, {"endTime", type datetimezone}, {"instanceId", type text}, {"machineNumber", type text}, {"localizedSource.", type text}, {"de-DE", type text}, {"en-US", type text}, {"category", type text}, {"sourceClass", type text}, {"sourceInstance", type text}, {"causality", type text}, {"severity", Int64.Type}, {"sourceMessageId", Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"startTime", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

