using Newtonsoft.Json;
using System.ComponentModel;

// Note: This is preliminary code and is subject to change

namespace HomagConnect.OrderManager.Contracts.OrderItems;

/// <summary>
/// An order position.
/// </summary>
public class Position : Base
{
    /// <summary>
    /// Gets or sets the name.
    /// </summary>
    [JsonProperty(Order = 1)]
    public string? Name { get; set; }

    /// <inheritdoc />
    public override Type Type
    {
        get
        {
            return Type.Position;
        }
        set
        {
            // Ignore
        }
    }

    /// <summary>
    /// Gets or sets the position number associated with the entity.
    /// This must be unique within an order.
    /// It is shown in every place where the position is referenced.
    /// If not set, it can be generated by the system.
    /// </summary>
    [JsonProperty(Order = 1)]
    public string? PositionNumber { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the item is hidden.
    /// This position is never shown in the order overview or printed documents.
    /// </summary>
    [JsonProperty(Order = 10)]
    public bool? IsHidden { get; set; }

    /// <summary>
    /// Gets or sets the article number.
    /// </summary>
    [JsonProperty(Order = 2)]
    public string? ArticleNumber { get; set; }

    /// <summary>
    /// Gets or sets the article name.
    /// </summary>
    [JsonProperty(Order = 2)]
    public string? ArticleName { get; set; }

    /// <summary>
    /// Gets or sets the description.
    /// </summary>
    [JsonProperty(Order = 3)]
    public string? Description { get; set; }

    /// <summary>
    /// Gets or sets the catalog.
    /// </summary>
    [JsonProperty(Order = 3)]
    public string? Catalog { get; set; }

    /// <summary>
    /// Gets or sets the quantity.
    /// </summary>
    [JsonProperty(Order = 4)]
    public int Quantity { get; set; } = 1;

    /// <summary>
    /// Gets or sets the height.
    /// </summary>
    [JsonProperty(Order = 5)]
    public double? Height { get; set; }

    /// <summary>
    /// Gets or sets the width.
    /// </summary>
    [JsonProperty(Order = 6)]
    public double? Width { get; set; }

    /// <summary>
    /// Gets or sets the depth.
    /// </summary>
    [JsonProperty(Order = 7)]
    public double? Depth { get; set; }


    /// <summary>
    /// Gets or sets the color.
    /// </summary>
    [JsonProperty(Order = 8)]
    public string? Color { get; set; }

    /// <summary>
    /// Gets or sets the corpus color.
    /// </summary>
    [JsonProperty(Order = 8)]
    public string? CarcaseColor { get; set; }

    /// <summary>
    /// Gets or sets the door direction.
    /// </summary>
    [JsonProperty(Order = 8)]
    public string? DoorDirection { get; set; }

    /// <summary>
    /// Gets or sets the procurement type.
    /// Values:
    /// * PTO - Purchase to order
    /// * MTO - Make to order
    /// * MTS - Make to stock
    /// </summary>
    [JsonProperty(Order = 9)]
    public string? ProcurementType { get; set; }

    /// <summary>
    /// Gets or sets the type of position associated with the current instance.
    /// Default is <seealso cref="PositionType.Standard"/>, if not specified.
    /// </summary>
    [JsonProperty(Order = 10)]
    public PositionType? PositionType { get; set; }

    /// <summary>
    /// Gets or sets the state of the entity.
    /// </summary>
    [JsonProperty(Order = 2)]
    [DefaultValue(State.New)]
    public State State { get; set; } = State.New;
}