//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.OrderManager.Contracts.OrderItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReclaimReasonDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReclaimReasonDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.OrderManager.Contracts.OrderItems.ReclaimReasonDisplayNames", typeof(ReclaimReasonDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platte beschädigt.
        /// </summary>
        public static string DamagedBoard {
            get {
                return ResourceManager.GetString("DamagedBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanten beschädigt.
        /// </summary>
        public static string DamagedEdges {
            get {
                return ResourceManager.GetString("DamagedEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohrungen nicht korrekt.
        /// </summary>
        public static string IncorrectDrillings {
            get {
                return ResourceManager.GetString("IncorrectDrillings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht geliefert.
        /// </summary>
        public static string NotDelivered {
            get {
                return ResourceManager.GetString("NotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstiges.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kratzer.
        /// </summary>
        public static string Scratches {
            get {
                return ResourceManager.GetString("Scratches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberflächenfehler.
        /// </summary>
        public static string SurfaceDefects {
            get {
                return ResourceManager.GetString("SurfaceDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausrisse.
        /// </summary>
        public static string Tearouts {
            get {
                return ResourceManager.GetString("Tearouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportschaden.
        /// </summary>
        public static string TransportDamage {
            get {
                return ResourceManager.GetString("TransportDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falschlieferung.
        /// </summary>
        public static string WrongDelivery {
            get {
                return ResourceManager.GetString("WrongDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche Abmessungen.
        /// </summary>
        public static string WrongDimensions {
            get {
                return ResourceManager.GetString("WrongDimensions", resourceCulture);
            }
        }
    }
}
