jobs:
- template: pipelines/templates/jobs/detect-changed-resx-files-job.yml
- template: pipelines/templates/jobs/translate-changed-resx-files-job.yml
- template: pipelines/templates/jobs/build-job.yml
