//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.MaterialManager.Contracts.Material.Edgebands.Enumerations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EdgebandMaterialCategoryDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EdgebandMaterialCategoryDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.MaterialManager.Contracts.Material.Edgebands.Enumerations.EdgebandMa" +
                            "terialCategoryDisplayNames", typeof(EdgebandMaterialCategoryDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS.
        /// </summary>
        public static string ABS {
            get {
                return ResourceManager.GetString("ABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acryl.
        /// </summary>
        public static string Acrylic {
            get {
                return ResourceManager.GetString("Acrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminum.
        /// </summary>
        public static string Aluminum {
            get {
                return ResourceManager.GetString("Aluminum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melamin.
        /// </summary>
        public static string Melamine {
            get {
                return ResourceManager.GetString("Melamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMMA.
        /// </summary>
        public static string PMMA {
            get {
                return ResourceManager.GetString("PMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP.
        /// </summary>
        public static string PP {
            get {
                return ResourceManager.GetString("PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVC.
        /// </summary>
        public static string PVC {
            get {
                return ResourceManager.GetString("PVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echtholz.
        /// </summary>
        public static string RealWood {
            get {
                return ResourceManager.GetString("RealWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnier.
        /// </summary>
        public static string Veneer {
            get {
                return ResourceManager.GetString("Veneer", resourceCulture);
            }
        }
    }
}
