table currentState
	lineageTag: bac655a8-1421-4187-9470-cbee10bec648

	column timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 7d002209-d3b4-4ae3-a507-be1e850dd8a3
		summarizeBy: none
		sourceColumn: timestamp

		variation Variation
			isDefault
			relationship: 1b349af3-e6e9-47c7-ac88-1eccd323bb9c
			defaultHierarchy: LocalDateTable_f1210d3c-8958-4b2e-87f0-381fbdcc4dcf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		lineageTag: b55e85a7-545f-4f9c-ba3a-ed28666c8184
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column Duration = datediff(currentState[timestamp],currentState[Inserted Addition.timestamp],second)
		formatString: 0
		lineageTag: 0e961322-4548-463d-a0ef-d753397b978b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Inserted Addition.timestamp'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4543eb85-f852-4368-8f7d-f2d33c96fbd8
		summarizeBy: none
		sourceColumn: Inserted Addition.timestamp

		variation Variation
			isDefault
			relationship: c12ba0e3-e309-48ad-9472-ca9780486a04
			defaultHierarchy: LocalDateTable_f7b8533a-54ad-4c0b-bbf5-bdf3f5a0d8ba.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition currentState = m
		mode: import
		source =
				let
				    Source = HistoricalData,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([node] = "Machines.State.Machine.Overview.CurrentState")),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows",{{"timestamp", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 0, 1, Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Index",{"value_numeric"}),
				    #"Inserted Addition" = Table.AddColumn(#"Removed Columns", "Addition", each [Index] + 1, type number),
				    #"Merged Queries" = Table.NestedJoin(#"Inserted Addition", {"Addition"}, #"Inserted Addition", {"Index"}, "Inserted Addition", JoinKind.LeftOuter),
				    #"Expanded Inserted Addition" = Table.ExpandTableColumn(#"Merged Queries", "Inserted Addition", {"timestamp"}, {"Inserted Addition.timestamp"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Inserted Addition",{"node", "Index", "Addition"})
				in
				    #"Removed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

