//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.MmrMobile.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlertEventCausalityDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertEventCausalityDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.MmrMobile.Contracts.AlertEventCausalityDisplayNames", typeof(AlertEventCausalityDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerung Maschine.
        /// </summary>
        public static string MachineControl {
            get {
                return ResourceManager.GetString("MachineControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektrik Maschine.
        /// </summary>
        public static string MachineElectric {
            get {
                return ResourceManager.GetString("MachineElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanik Maschine.
        /// </summary>
        public static string MachineMechanic {
            get {
                return ResourceManager.GetString("MachineMechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkmodus.
        /// </summary>
        public static string PlantMode {
            get {
                return ResourceManager.GetString("PlantMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versorgung.
        /// </summary>
        public static string Supply {
            get {
                return ResourceManager.GetString("Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absaugung Versorgung.
        /// </summary>
        public static string SupplyAirSuction {
            get {
                return ResourceManager.GetString("SupplyAirSuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckluft Versorgung.
        /// </summary>
        public static string SupplyCompressedAir {
            get {
                return ResourceManager.GetString("SupplyCompressedAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenversorgung.
        /// </summary>
        public static string SupplyData {
            get {
                return ResourceManager.GetString("SupplyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektrik Versorgung.
        /// </summary>
        public static string SupplyElectric {
            get {
                return ResourceManager.GetString("SupplyElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restholzversorgung.
        /// </summary>
        public static string SupplyOffcut {
            get {
                return ResourceManager.GetString("SupplyOffcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlende Hilfsstoffe.
        /// </summary>
        public static string UserLackAuxilarySupplies {
            get {
                return ResourceManager.GetString("UserLackAuxilarySupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartung.
        /// </summary>
        public static string UserMaintenance {
            get {
                return ResourceManager.GetString("UserMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedienung.
        /// </summary>
        public static string UserOperational {
            get {
                return ResourceManager.GetString("UserOperational", resourceCulture);
            }
        }
    }
}
