<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
		<LangVersion>default</LangVersion>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>HomagGroup.HomagConnect.MmrMobile.Contracts</PackageId>
		<Title>Homag-Connect MMR Mobile Contracts</Title>
		<Description>Client assembly for the usage of Homag-Connect MMR Mobile API</Description>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
		<PackageProjectUrl>https://github.com/HomagGroup/HOMAG-Connect/tree/main/Applications/MmrMobile/Contracts</PackageProjectUrl>
		<RepositoryUrl>https://github.com/HomagGroup/HOMAG-Connect</RepositoryUrl>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<EmbedAllSources>true</EmbedAllSources>
		<DebugType>Embedded</DebugType>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Base\HomagConnect.Base.Contracts\HomagConnect.Base.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="MmrPropertyDisplayNames.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>MmrPropertyDisplayNames.resx</DependentUpon>
		</Compile>
		<Compile Update="GranularityDisplayNames.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>GranularityDisplayNames.resx</DependentUpon>
		</Compile>
		<Compile Update="AlertEventCategoryDisplayNames.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AlertEventCategoryDisplayNames.resx</DependentUpon>
		</Compile>
		<Compile Update="AlertEventCausalityDisplayNames.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AlertEventCausalityDisplayNames.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="MmrPropertyDisplayNames.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>MmrPropertyDisplayNames.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="GranularityDisplayNames.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>GranularityDisplayNames.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="AlertEventCategoryDisplayNames.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>AlertEventCategoryDisplayNames.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="AlertEventCausalityDisplayNames.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>AlertEventCausalityDisplayNames.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
