//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.MmrMobile.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MmrPropertyDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MmrPropertyDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.MmrMobile.Contracts.MmrPropertyDisplayNames", typeof(MmrPropertyDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zähler.
        /// </summary>
        public static string CounterTranslation {
            get {
                return ResourceManager.GetString("CounterTranslation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verursacher.
        /// </summary>
        public static string Causality {
            get {
                return ResourceManager.GetString("Causality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string DetailedStateTranslation {
            get {
                return ResourceManager.GetString("DetailedStateTranslation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dauer [h].
        /// </summary>
        public static string DurationInHours {
            get {
                return ResourceManager.GetString("DurationInHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endzeitpunkt.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Granularität.
        /// </summary>
        public static string Granularity {
            get {
                return ResourceManager.GetString("Granularity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Instanz.
        /// </summary>
        public static string InstanceId {
            get {
                return ResourceManager.GetString("InstanceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lokalisierte Meldung.
        /// </summary>
        public static string LocalizedMessage {
            get {
                return ResourceManager.GetString("LocalizedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lokalisierte Quelle.
        /// </summary>
        public static string LocalizedSource {
            get {
                return ResourceManager.GetString("LocalizedSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maschinenname.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maschinennummer.
        /// </summary>
        public static string MachineNumber {
            get {
                return ResourceManager.GetString("MachineNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maschinentyp.
        /// </summary>
        public static string MachineType {
            get {
                return ResourceManager.GetString("MachineType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Knoten.
        /// </summary>
        public static string Nodes {
            get {
                return ResourceManager.GetString("Nodes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Knotenname.
        /// </summary>
        public static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zustand.
        /// </summary>
        public static string StateTranslation {
            get {
                return ResourceManager.GetString("StateTranslation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quellinstanz.
        /// </summary>
        public static string SourceInstance {
            get {
                return ResourceManager.GetString("SourceInstance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quellklasse.
        /// </summary>
        public static string SourceClass {
            get {
                return ResourceManager.GetString("SourceClass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quellnachrichten-ID.
        /// </summary>
        public static string SourceMessageId {
            get {
                return ResourceManager.GetString("SourceMessageId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schweregrad.
        /// </summary>
        public static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Startzeitpunkt.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zeitstempel.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Einheit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wert.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
