//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.ProductionManager.Contracts.Rework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReworkReasonDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReworkReasonDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.ProductionManager.Contracts.Rework.ReworkReasonDisplayNames", typeof(ReworkReasonDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brandspuren.
        /// </summary>
        public static string BurnMarks {
            get {
                return ResourceManager.GetString("BurnMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rattermarken.
        /// </summary>
        public static string ChatterMarks {
            get {
                return ResourceManager.GetString("ChatterMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufspannung nicht OK.
        /// </summary>
        public static string ClampingNotOK {
            get {
                return ResourceManager.GetString("ClampingNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platte beschädigt.
        /// </summary>
        public static string DamagedBoard {
            get {
                return ResourceManager.GetString("DamagedBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschädigung.
        /// </summary>
        public static string Damages {
            get {
                return ResourceManager.GetString("Damages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmessungen nicht OK.
        /// </summary>
        public static string DimensionsNotOK {
            get {
                return ResourceManager.GetString("DimensionsNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohrbild gespiegelt.
        /// </summary>
        public static string DrillingPatternMirrored {
            get {
                return ResourceManager.GetString("DrillingPatternMirrored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachfertigung nicht OK.
        /// </summary>
        public static string FinishingNotOK {
            get {
                return ResourceManager.GetString("FinishingNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschlüsse.
        /// </summary>
        public static string Inclusions {
            get {
                return ResourceManager.GetString("Inclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstige.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teil beschädigt.
        /// </summary>
        public static string PartDamaged {
            get {
                return ResourceManager.GetString("PartDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teil verloren.
        /// </summary>
        public static string PartLost {
            get {
                return ResourceManager.GetString("PartLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teil außerhalb Toleranz.
        /// </summary>
        public static string PartOutOfTolerance {
            get {
                return ResourceManager.GetString("PartOutOfTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschmutzung.
        /// </summary>
        public static string Pollution {
            get {
                return ResourceManager.GetString("Pollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kratzer.
        /// </summary>
        public static string Scratches {
            get {
                return ResourceManager.GetString("Scratches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausrisse.
        /// </summary>
        public static string Tearouts {
            get {
                return ResourceManager.GetString("Tearouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu wenig Leim.
        /// </summary>
        public static string TooLittleGlue {
            get {
                return ResourceManager.GetString("TooLittleGlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkzeug falsch eingemessen.
        /// </summary>
        public static string ToolMeasuredIncorrectly {
            get {
                return ResourceManager.GetString("ToolMeasuredIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellenschnitt.
        /// </summary>
        public static string WaveCut {
            get {
                return ResourceManager.GetString("WaveCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches CNC-Programm/ Bohrbild.
        /// </summary>
        public static string WrongCNCProgramOrDrillingPattern {
            get {
                return ResourceManager.GetString("WrongCNCProgramOrDrillingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Kantenmaterial.
        /// </summary>
        public static string WrongEdgeMaterial {
            get {
                return ResourceManager.GetString("WrongEdgeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Material.
        /// </summary>
        public static string WrongMaterial {
            get {
                return ResourceManager.GetString("WrongMaterial", resourceCulture);
            }
        }
    }
}
