//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.MaterialManager.Contracts.Material.Boards.Enumerations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BoardMaterialCategoryDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoardMaterialCategoryDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.MaterialManager.Contracts.Material.Boards.Enumerations.BoardMaterial" +
                            "CategoryDisplayNames", typeof(BoardMaterialCategoryDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrylgebundene Mineralwerkstoffe.
        /// </summary>
        public static string AcrylicCompositeMaterials {
            get {
                return ResourceManager.GetString("AcrylicCompositeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrylglas (PMMA).
        /// </summary>
        public static string AcrylicGlass_PMMA {
            get {
                return ResourceManager.GetString("AcrylicGlass_PMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Mg-Cu.
        /// </summary>
        public static string AlMgCu {
            get {
                return ResourceManager.GetString("AlMgCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Si-Legierung.
        /// </summary>
        public static string AlSiAlloy {
            get {
                return ResourceManager.GetString("AlSiAlloy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium.
        /// </summary>
        public static string Aluminum {
            get {
                return ResourceManager.GetString("Aluminum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium-Wabenplatten.
        /// </summary>
        public static string AluminumHoneycombPanels {
            get {
                return ResourceManager.GetString("AluminumHoneycombPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stab- &amp; Stäbchensperrholz (Hartholz).
        /// </summary>
        public static string BlockboardAndLaminboard_HardWood {
            get {
                return ResourceManager.GetString("BlockboardAndLaminboard_HardWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stab- &amp; Stäbchensperrholz (Weichholz).
        /// </summary>
        public static string BlockboardAndLaminboard_SoftWood {
            get {
                return ResourceManager.GetString("BlockboardAndLaminboard_SoftWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butylkautschuk (IIR).
        /// </summary>
        public static string ButylRubber_IIR {
            get {
                return ResourceManager.GetString("ButylRubber_IIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kohlenstofffaserverstärkter Kunststoff (CFK).
        /// </summary>
        public static string CarbonfibrereinforcedPlastics_CFK {
            get {
                return ResourceManager.GetString("CarbonfibrereinforcedPlastics_CFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zementgebundene Platten.
        /// </summary>
        public static string CementboundPanels {
            get {
                return ResourceManager.GetString("CementboundPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanplatte.
        /// </summary>
        public static string Chipboard {
            get {
                return ResourceManager.GetString("Chipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompaktplatten (HPL).
        /// </summary>
        public static string CompactPanels_HPL {
            get {
                return ResourceManager.GetString("CompactPanels_HPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbundplatten mit Aluminium.
        /// </summary>
        public static string CompositePanelsWithAluminum {
            get {
                return ResourceManager.GetString("CompositePanelsWithAluminum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Polymer-gebundene Mineralwerkstoffe.
        /// </summary>
        public static string CopolymerboundMineralMaterials {
            get {
                return ResourceManager.GetString("CopolymerboundMineralMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupfer, Zink, Messing.
        /// </summary>
        public static string CopperZincBrass {
            get {
                return ResourceManager.GetString("CopperZincBrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glasfaserverstärkter Kunststoff (GFK).
        /// </summary>
        public static string FibreglassReinforcedPlastics_GFRP {
            get {
                return ResourceManager.GetString("FibreglassReinforcedPlastics_GFRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grobspanplatte (OSB-Platte).
        /// </summary>
        public static string Flakeboard_OSBPanel {
            get {
                return ResourceManager.GetString("Flakeboard_OSBPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leimholzplatte/Brettschichtholz (Hartholz).
        /// </summary>
        public static string GluedWoodPanelGluelaminatedWood_HardWood {
            get {
                return ResourceManager.GetString("GluedWoodPanelGluelaminatedWood_HardWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leimholzplatte/Brettschichtholz (Weichholz).
        /// </summary>
        public static string GluedWoodPanelGluelaminatedWood_SoftWood {
            get {
                return ResourceManager.GetString("GluedWoodPanelGluelaminatedWood_SoftWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gipskartonplatten (Gipsplatten).
        /// </summary>
        public static string GypsumPlasterboard_Plasterboard {
            get {
                return ResourceManager.GetString("GypsumPlasterboard_Plasterboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hartschaumplatte.
        /// </summary>
        public static string HardFoamPanel {
            get {
                return ResourceManager.GetString("HardFoamPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hartpapier (HP).
        /// </summary>
        public static string HardPaper_HP {
            get {
                return ResourceManager.GetString("HardPaper_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hartfaserplatte.
        /// </summary>
        public static string HardParticleBoard {
            get {
                return ResourceManager.GetString("HardParticleBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hartholz quer.
        /// </summary>
        public static string HardwoodCrosswise {
            get {
                return ResourceManager.GetString("HardwoodCrosswise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hartholz längs.
        /// </summary>
        public static string HardwoodLengthwise {
            get {
                return ResourceManager.GetString("HardwoodLengthwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochdichte Faserplatte (HDF).
        /// </summary>
        public static string HighdensityFiberboard_HDF {
            get {
                return ResourceManager.GetString("HighdensityFiberboard_HDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integralschaumplatte.
        /// </summary>
        public static string IntegralFoamPanel {
            get {
                return ResourceManager.GetString("IntegralFoamPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminat.
        /// </summary>
        public static string Laminate {
            get {
                return ResourceManager.GetString("Laminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schichtstoff (HPL).
        /// </summary>
        public static string Laminate_HPL {
            get {
                return ResourceManager.GetString("Laminate_HPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hartgewebe (HGW).
        /// </summary>
        public static string LaminatedFabric_HGW {
            get {
                return ResourceManager.GetString("LaminatedFabric_HGW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminatfußbodenplatten.
        /// </summary>
        public static string LaminateFlooringPanels {
            get {
                return ResourceManager.GetString("LaminateFlooringPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blei-Legierung.
        /// </summary>
        public static string LeadAlloy {
            get {
                return ResourceManager.GetString("LeadAlloy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichtbauplatte mit Spanplatten.
        /// </summary>
        public static string LightweightPanelWithChipboard {
            get {
                return ResourceManager.GetString("LightweightPanelWithChipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichtbauplatte mit MDF-Platten.
        /// </summary>
        public static string LightweightPanelWithMdfBoards {
            get {
                return ResourceManager.GetString("LightweightPanelWithMdfBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leicht schmelzende Thermoplaste (PP, PA).
        /// </summary>
        public static string LowmeltingThermoplastics_PP_PA {
            get {
                return ResourceManager.GetString("LowmeltingThermoplastics_PP_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitteldichte Faserplatte (MDF).
        /// </summary>
        public static string MediumdensityFiberboard_MDF {
            get {
                return ResourceManager.GetString("MediumdensityFiberboard_MDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturkautschuk (NR).
        /// </summary>
        public static string NaturalRubber_NR {
            get {
                return ResourceManager.GetString("NaturalRubber_NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phenolformaldehyd (PF).
        /// </summary>
        public static string PhenolFormaldehyde_PF {
            get {
                return ResourceManager.GetString("PhenolFormaldehyde_PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siebdruckplatte.
        /// </summary>
        public static string PhenolicResinCoatedPlywood {
            get {
                return ResourceManager.GetString("PhenolicResinCoatedPlywood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunststoff-Wabenplatten.
        /// </summary>
        public static string PlasticHoneycombPanels {
            get {
                return ResourceManager.GetString("PlasticHoneycombPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniersperrholz (Multiplex-Platte).
        /// </summary>
        public static string Plywood_MultiplexPanel {
            get {
                return ResourceManager.GetString("Plywood_MultiplexPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyestergebundene Mineralwerkstoffe.
        /// </summary>
        public static string PolyesterboundMineralMaterials {
            get {
                return ResourceManager.GetString("PolyesterboundMineralMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyvinylcarbazol (PUK).
        /// </summary>
        public static string PolyvinylCarbazole_PVK {
            get {
                return ResourceManager.GetString("PolyvinylCarbazole_PVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weichfaserplatte.
        /// </summary>
        public static string SoftFiberboard {
            get {
                return ResourceManager.GetString("SoftFiberboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weichholz quer.
        /// </summary>
        public static string SoftwoodCrosswise {
            get {
                return ResourceManager.GetString("SoftwoodCrosswise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weichholz längs.
        /// </summary>
        public static string SoftwoodLengthwise {
            get {
                return ResourceManager.GetString("SoftwoodLengthwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styrol-Butadien-Kautschuk (SBR).
        /// </summary>
        public static string StyrenebutadieneRubber_SBR {
            get {
                return ResourceManager.GetString("StyrenebutadieneRubber_SBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermoplaste (PE, PVC, ABS, POM, PS).
        /// </summary>
        public static string Thermoplastics {
            get {
                return ResourceManager.GetString("Thermoplastics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dreischichtplatte, Brettsperrholzplatte (Hartholz).
        /// </summary>
        public static string ThreelayerPanelLaminatedTimberPanels_HardWood {
            get {
                return ResourceManager.GetString("ThreelayerPanelLaminatedTimberPanels_HardWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dreischichtplatte, Brettsperrholzplatte (Weichholz).
        /// </summary>
        public static string ThreelayerPanelLaminatedTimberPanels_SoftWood {
            get {
                return ResourceManager.GetString("ThreelayerPanelLaminatedTimberPanels_SoftWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefiniert.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnier.
        /// </summary>
        public static string Veneer {
            get {
                return ResourceManager.GetString("Veneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood-Plastic-Composites (WPC).
        /// </summary>
        public static string WoodplasticComposites_WPC {
            get {
                return ResourceManager.GetString("WoodplasticComposites_WPC", resourceCulture);
            }
        }
    }
}
