//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.MaterialManager.Contracts.Material.Boards.Enumerations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoardMaterialCategoryDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoardMaterialCategoryDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.MaterialManager.Contracts.Material.Boards.Enumerations.BoardMaterial" +
                            "CategoryDisplayNames", typeof(BoardMaterialCategoryDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrylic composite materials.
        /// </summary>
        internal static string AcrylicCompositeMaterials {
            get {
                return ResourceManager.GetString("AcrylicCompositeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrylglas (PMMA).
        /// </summary>
        internal static string AcrylicGlass_PMMA {
            get {
                return ResourceManager.GetString("AcrylicGlass_PMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Mg-Cu.
        /// </summary>
        internal static string AlMgCu {
            get {
                return ResourceManager.GetString("AlMgCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Si-Legierung.
        /// </summary>
        internal static string AlSiAlloy {
            get {
                return ResourceManager.GetString("AlSiAlloy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium.
        /// </summary>
        internal static string Aluminum {
            get {
                return ResourceManager.GetString("Aluminum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanplatte.
        /// </summary>
        internal static string Chipboard {
            get {
                return ResourceManager.GetString("Chipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompaktplatten (HPL).
        /// </summary>
        internal static string CompactPanels_HPL {
            get {
                return ResourceManager.GetString("CompactPanels_HPL", resourceCulture);
            }
        }
    }
}
