table Counters
	lineageTag: bf54a0f1-938c-4741-994f-2e57df97d300

	column 'Machine Number'
		dataType: string
		lineageTag: abce71de-9004-490d-96a6-6099c3520aca
		summarizeBy: none
		sourceColumn: Machine Number

		annotation SummarizationSetBy = Automatic

	column 'Machine Name'
		dataType: string
		lineageTag: 73a8100a-c7e5-4ffa-9ec8-a9c462bd72c1
		summarizeBy: none
		sourceColumn: Machine Name

		annotation SummarizationSetBy = Automatic

	column 'Machine Type'
		dataType: string
		lineageTag: 75aef6d3-eb22-47b1-be1f-44ab4007916d
		summarizeBy: none
		sourceColumn: Machine Type

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: f27d5bf8-91c8-4bf3-b89d-bf16b2393869
		summarizeBy: none
		sourceColumn: Timestamp

		variation Variation
			isDefault
			relationship: cb2856df-c3e0-4756-ade2-b9d8e897ef3e
			defaultHierarchy: LocalDateTable_3f8afd58-0e94-4d1d-baee-897587a182fb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 0adf8d0c-9949-4fde-8d0c-a62a7e0e9cb7
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Instance Id'
		dataType: string
		lineageTag: 71beac5b-d195-4bcb-95f3-d58b162ba479
		summarizeBy: none
		sourceColumn: Instance Id

		annotation SummarizationSetBy = Automatic

	column 'Counter Id'
		dataType: string
		lineageTag: 6e235e25-bc38-403e-bef3-32e4e472f900
		summarizeBy: none
		sourceColumn: Counter Id

		annotation SummarizationSetBy = Automatic

	column Counter
		dataType: string
		lineageTag: 6e73f3df-e3b0-48cd-bfc8-c1361dbc0494
		summarizeBy: none
		sourceColumn: Counter

		annotation SummarizationSetBy = Automatic

	partition Counters-42ab0698-e1dd-4263-8924-c908b689afb2 = m
		mode: import
		queryGroup: Counter
		source =
				let
				    RawDocument = Web.Contents("https://connect.homag.cloud/api/mmr-mobile/counters?daysBack=90"),
				    JsonDocument = Json.Document(RawDocument ),
				    JsonAsTable = Table.FromList(JsonDocument, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    CounterList = Table.ExpandRecordColumn(JsonAsTable, "Column1", {"Machine Number", "Machine Name", "Machine Type", "Timestamp", "Value", "Instance Id", "Counter Id", "Counter"}, {"Machine Number", "Machine Name", "Machine Type", "Timestamp", "Value", "Instance Id", "Counter Id", "Counter"}),
				    ChangedStringDate = Table.TransformColumnTypes(CounterList,{{"Timestamp", type datetime},{"Machine Number", type text}, {"Machine Name", type text}, {"Machine Type", type text}, {"Instance Id", type text}, {"Counter Id", type text}, {"Counter", type text}}),
				    ChangedNumbers = Table.TransformColumnTypes(ChangedStringDate, {{"Value", type number}}, "en-US")
				in
				    ChangedNumbers

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

