//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.MaterialManager.Contracts.Surfaces.Textures.DecorMatches {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DecorMatchDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DecorMatchDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.MaterialManager.Contracts.Surfaces.Textures.DecorMatches.DecorMatchD" +
                            "isplayNames", typeof(DecorMatchDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandidaten.
        /// </summary>
        public static string Candidates {
            get {
                return ResourceManager.GetString("Candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfidenzwert.
        /// </summary>
        public static string ConfidenceScore {
            get {
                return ResourceManager.GetString("ConfidenceScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekor-ID.
        /// </summary>
        public static string DecorId {
            get {
                return ResourceManager.GetString("DecorId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        public static string LocalizedName {
            get {
                return ResourceManager.GetString("LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschaubilder.
        /// </summary>
        public static string Previews {
            get {
                return ResourceManager.GetString("Previews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textur-URL.
        /// </summary>
        public static string TextureUri {
            get {
                return ResourceManager.GetString("TextureUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtanzahl.
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
    }
}
