//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.Base.Contracts.Enumerations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MachineBaseTypeDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MachineBaseTypeDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.Base.Contracts.Enumerations.MachineBaseTypeDisplayNames", typeof(MachineBaseTypeDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montieren.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNC.
        /// </summary>
        public static string Cnc {
            get {
                return ResourceManager.GetString("Cnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohren.
        /// </summary>
        public static string Drilling {
            get {
                return ResourceManager.GetString("Drilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kantenanleimen.
        /// </summary>
        public static string Edge {
            get {
                return ResourceManager.GetString("Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling.
        /// </summary>
        public static string Handling {
            get {
                return ResourceManager.GetString("Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminieren.
        /// </summary>
        public static string Lamination {
            get {
                return ResourceManager.GetString("Lamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobeln.
        /// </summary>
        public static string Moulding {
            get {
                return ResourceManager.GetString("Moulding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verpacken.
        /// </summary>
        public static string Packaging {
            get {
                return ResourceManager.GetString("Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vormontieren.
        /// </summary>
        public static string PreAssembly {
            get {
                return ResourceManager.GetString("PreAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schleifen.
        /// </summary>
        public static string Sanding {
            get {
                return ResourceManager.GetString("Sanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sägen.
        /// </summary>
        public static string Saw {
            get {
                return ResourceManager.GetString("Saw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versand.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortieren.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagern.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagern.
        /// </summary>
        public static string Storing {
            get {
                return ResourceManager.GetString("Storing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
