//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.Base.Contracts.Enumerations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkstationGroupDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkstationGroupDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.Base.Contracts.Enumerations.WorkstationGroupDisplayNames", typeof(WorkstationGroupDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montieren.
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platten.
        /// </summary>
        internal static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNC.
        /// </summary>
        internal static string CNC {
            get {
                return ResourceManager.GetString("CNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufteilen.
        /// </summary>
        internal static string Dividing {
            get {
                return ResourceManager.GetString("Dividing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kantenanleimen.
        /// </summary>
        internal static string Edgebanding {
            get {
                return ResourceManager.GetString("Edgebanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminieren.
        /// </summary>
        internal static string Laminating {
            get {
                return ResourceManager.GetString("Laminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobeln.
        /// </summary>
        internal static string Moulding {
            get {
                return ResourceManager.GetString("Moulding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verpacken.
        /// </summary>
        internal static string Packaging {
            get {
                return ResourceManager.GetString("Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vormontieren.
        /// </summary>
        internal static string Preassembly {
            get {
                return ResourceManager.GetString("Preassembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachfertigung.
        /// </summary>
        internal static string Rework {
            get {
                return ResourceManager.GetString("Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walzenbeschichtung.
        /// </summary>
        internal static string RollerCoating {
            get {
                return ResourceManager.GetString("RollerCoating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schleifen.
        /// </summary>
        internal static string Sanding {
            get {
                return ResourceManager.GetString("Sanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versand.
        /// </summary>
        internal static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortieren.
        /// </summary>
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortieren nach Aufteilen.
        /// </summary>
        internal static string SortingAfterCutting {
            get {
                return ResourceManager.GetString("SortingAfterCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lackieren.
        /// </summary>
        internal static string SprayCoating {
            get {
                return ResourceManager.GetString("SprayCoating", resourceCulture);
            }
        }
    }
}
