//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.Base.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.Base.Contracts.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusatzdaten.
        /// </summary>
        public static string AllocationProperties_AdditionalData {
            get {
                return ResourceManager.GetString("AllocationProperties_AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusatzdaten.
        /// </summary>
        public static string AllocationProperties_AdditionalProperties {
            get {
                return ResourceManager.GetString("AllocationProperties_AdditionalProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentare.
        /// </summary>
        public static string AllocationProperties_Comments {
            get {
                return ResourceManager.GetString("AllocationProperties_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am.
        /// </summary>
        public static string AllocationProperties_CreatedAt {
            get {
                return ResourceManager.GetString("AllocationProperties_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt von.
        /// </summary>
        public static string AllocationProperties_CreatedBy {
            get {
                return ResourceManager.GetString("AllocationProperties_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservierung.
        /// </summary>
        public static string AllocationProperties_Name {
            get {
                return ResourceManager.GetString("AllocationProperties_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle.
        /// </summary>
        public static string AllocationProperties_Source {
            get {
                return ResourceManager.GetString("AllocationProperties_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplatz.
        /// </summary>
        public static string AllocationProperties_Workstation {
            get {
                return ResourceManager.GetString("AllocationProperties_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattentyp.
        /// </summary>
        public static string BoardEntityProperties_BoardType {
            get {
                return ResourceManager.GetString("BoardEntityProperties_BoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkungen (Platte).
        /// </summary>
        public static string BoardEntityProperties_Comments {
            get {
                return ResourceManager.GetString("BoardEntityProperties_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellungsdatum.
        /// </summary>
        public static string BoardEntityProperties_CreationDate {
            get {
                return ResourceManager.GetString("BoardEntityProperties_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge.
        /// </summary>
        public static string BoardEntityProperties_Length {
            get {
                return ResourceManager.GetString("BoardEntityProperties_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerplatz.
        /// </summary>
        public static string BoardEntityProperties_Location {
            get {
                return ResourceManager.GetString("BoardEntityProperties_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltungstyp.
        /// </summary>
        public static string BoardEntityProperties_ManagementType {
            get {
                return ResourceManager.GetString("BoardEntityProperties_ManagementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string BoardEntityProperties_Quantity {
            get {
                return ResourceManager.GetString("BoardEntityProperties_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        public static string BoardEntityProperties_Width {
            get {
                return ResourceManager.GetString("BoardEntityProperties_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattencode.
        /// </summary>
        public static string BoardTypeAllocationProperties_BoardCode {
            get {
                return ResourceManager.GetString("BoardTypeAllocationProperties_BoardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string BoardTypeAllocationProperties_Quantity {
            get {
                return ResourceManager.GetString("BoardTypeAllocationProperties_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusatzdaten.
        /// </summary>
        public static string BoardTypeDetailsProperties_AdditionalData {
            get {
                return ResourceManager.GetString("BoardTypeDetailsProperties_AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservierung.
        /// </summary>
        public static string BoardTypeDetailsProperties_Allocations {
            get {
                return ResourceManager.GetString("BoardTypeDetailsProperties_Allocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand.
        /// </summary>
        public static string BoardTypeDetailsProperties_Inventory {
            get {
                return ResourceManager.GetString("BoardTypeDetailsProperties_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkung (Platte).
        /// </summary>
        public static string BoardTypeInventoryProperties_AdditionalCommentsBoards {
            get {
                return ResourceManager.GetString("BoardTypeInventoryProperties_AdditionalCommentsBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattencode.
        /// </summary>
        public static string BoardTypeInventoryProperties_Code {
            get {
                return ResourceManager.GetString("BoardTypeInventoryProperties_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellungsdatum.
        /// </summary>
        public static string BoardTypeInventoryProperties_CreationDate {
            get {
                return ResourceManager.GetString("BoardTypeInventoryProperties_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerplatz.
        /// </summary>
        public static string BoardTypeInventoryProperties_Location {
            get {
                return ResourceManager.GetString("BoardTypeInventoryProperties_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string BoardTypeInventoryProperties_Quantity {
            get {
                return ResourceManager.GetString("BoardTypeInventoryProperties_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplatz.
        /// </summary>
        public static string BoardTypeInventoryProperties_Workstation {
            get {
                return ResourceManager.GetString("BoardTypeInventoryProperties_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikelnummer.
        /// </summary>
        public static string BoardTypeProperties_ArticleNumber {
            get {
                return ResourceManager.GetString("BoardTypeProperties_ArticleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattencode.
        /// </summary>
        public static string BoardTypeProperties_BoardCode {
            get {
                return ResourceManager.GetString("BoardTypeProperties_BoardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string BoardTypeProperties_BoardTypeType {
            get {
                return ResourceManager.GetString("BoardTypeProperties_BoardTypeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschichtung.
        /// </summary>
        public static string BoardTypeProperties_CoatingCategory {
            get {
                return ResourceManager.GetString("BoardTypeProperties_CoatingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkungen (Stammdaten).
        /// </summary>
        public static string BoardTypeProperties_Comments {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten.
        /// </summary>
        public static string BoardTypeProperties_Costs {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekorcode.
        /// </summary>
        public static string BoardTypeProperties_DecorCode {
            get {
                return ResourceManager.GetString("BoardTypeProperties_DecorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekorname.
        /// </summary>
        public static string BoardTypeProperties_DecorName {
            get {
                return ResourceManager.GetString("BoardTypeProperties_DecorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichte.
        /// </summary>
        public static string BoardTypeProperties_Density {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prägung unten.
        /// </summary>
        public static string BoardTypeProperties_EmbossingBottom {
            get {
                return ResourceManager.GetString("BoardTypeProperties_EmbossingBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prägung oben.
        /// </summary>
        public static string BoardTypeProperties_EmbossingTop {
            get {
                return ResourceManager.GetString("BoardTypeProperties_EmbossingTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maserung.
        /// </summary>
        public static string BoardTypeProperties_Grain {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTIN.
        /// </summary>
        public static string BoardTypeProperties_Gtin {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Gtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestbestand unterschritten.
        /// </summary>
        public static string BoardTypeProperties_InsufficientInventory {
            get {
                return ResourceManager.GetString("BoardTypeProperties_InsufficientInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt verwendet.
        /// </summary>
        public static string BoardTypeProperties_LastUsed {
            get {
                return ResourceManager.GetString("BoardTypeProperties_LastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge.
        /// </summary>
        public static string BoardTypeProperties_Length {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattentyp für Optimierung gesperrt.
        /// </summary>
        public static string BoardTypeProperties_LockedForOptimization {
            get {
                return ResourceManager.GetString("BoardTypeProperties_LockedForOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hersteller.
        /// </summary>
        public static string BoardTypeProperties_ManufacturerName {
            get {
                return ResourceManager.GetString("BoardTypeProperties_ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string BoardTypeProperties_MaterialCategory {
            get {
                return ResourceManager.GetString("BoardTypeProperties_MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialcode.
        /// </summary>
        public static string BoardTypeProperties_MaterialCode {
            get {
                return ResourceManager.GetString("BoardTypeProperties_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material zuletzt verwendet.
        /// </summary>
        public static string BoardTypeProperties_MaterialLastUsed {
            get {
                return ResourceManager.GetString("BoardTypeProperties_MaterialLastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegen unendlich optimieren.
        /// </summary>
        public static string BoardTypeProperties_OptimizeAgainstInfinite {
            get {
                return ResourceManager.GetString("BoardTypeProperties_OptimizeAgainstInfinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktname.
        /// </summary>
        public static string BoardTypeProperties_ProductName {
            get {
                return ResourceManager.GetString("BoardTypeProperties_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardqualität.
        /// </summary>
        public static string BoardTypeProperties_StandardQuality {
            get {
                return ResourceManager.GetString("BoardTypeProperties_StandardQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dicke.
        /// </summary>
        public static string BoardTypeProperties_Thickness {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserviert.
        /// </summary>
        public static string BoardTypeProperties_TotalAreaAllocated {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalAreaAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbar.
        /// </summary>
        public static string BoardTypeProperties_TotalAreaAvailable {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalAreaAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestbestand.
        /// </summary>
        public static string BoardTypeProperties_TotalAreaAvailableWarningLimit {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalAreaAvailableWarningLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtfläche.
        /// </summary>
        public static string BoardTypeProperties_TotalAreaInInventory {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalAreaInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserviert.
        /// </summary>
        public static string BoardTypeProperties_TotalQuantityAllocated {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalQuantityAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbar.
        /// </summary>
        public static string BoardTypeProperties_TotalQuantityAvailable {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalQuantityAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestbestand.
        /// </summary>
        public static string BoardTypeProperties_TotalQuantityAvailableWarningLimit {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalQuantityAvailableWarningLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string BoardTypeProperties_TotalQuantityInInventory {
            get {
                return ResourceManager.GetString("BoardTypeProperties_TotalQuantityInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        public static string BoardTypeProperties_Width {
            get {
                return ResourceManager.GetString("BoardTypeProperties_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belag unten.
        /// </summary>
        public static string ILaminatingProperties_LaminateBottom {
            get {
                return ResourceManager.GetString("ILaminatingProperties_LaminateBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belag oben.
        /// </summary>
        public static string ILaminatingProperties_LaminateTop {
            get {
                return ResourceManager.GetString("ILaminatingProperties_LaminateTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusatzdaten.
        /// </summary>
        public static string MaterialProperties_AdditionalData {
            get {
                return ResourceManager.GetString("MaterialProperties_AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittskosten.
        /// </summary>
        public static string MaterialProperties_AverageCosts {
            get {
                return ResourceManager.GetString("MaterialProperties_AverageCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattenparameter für Optimierung.
        /// </summary>
        public static string MaterialProperties_BoardParameterForOptimization {
            get {
                return ResourceManager.GetString("MaterialProperties_BoardParameterForOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschichtung.
        /// </summary>
        public static string MaterialProperties_CoatingCategory {
            get {
                return ResourceManager.GetString("MaterialProperties_CoatingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialcode.
        /// </summary>
        public static string MaterialProperties_Code {
            get {
                return ResourceManager.GetString("MaterialProperties_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekorcode.
        /// </summary>
        public static string MaterialProperties_DecorCode {
            get {
                return ResourceManager.GetString("MaterialProperties_DecorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekorname.
        /// </summary>
        public static string MaterialProperties_DecorName {
            get {
                return ResourceManager.GetString("MaterialProperties_DecorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichte.
        /// </summary>
        public static string MaterialProperties_Density {
            get {
                return ResourceManager.GetString("MaterialProperties_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hersteller.
        /// </summary>
        public static string MaterialProperties_Manufacturer {
            get {
                return ResourceManager.GetString("MaterialProperties_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkungen (Stammdaten).
        /// </summary>
        public static string MaterialProperties_MasterDataComments {
            get {
                return ResourceManager.GetString("MaterialProperties_MasterDataComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string MaterialProperties_MaterialCategory {
            get {
                return ResourceManager.GetString("MaterialProperties_MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialparametergruppe für Optimierung.
        /// </summary>
        public static string MaterialProperties_MaterialParameterForOptimization {
            get {
                return ResourceManager.GetString("MaterialProperties_MaterialParameterForOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktname.
        /// </summary>
        public static string MaterialProperties_ProductName {
            get {
                return ResourceManager.GetString("MaterialProperties_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardqualität.
        /// </summary>
        public static string MaterialProperties_StandardQuality {
            get {
                return ResourceManager.GetString("MaterialProperties_StandardQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dicke.
        /// </summary>
        public static string MaterialProperties_Thickness {
            get {
                return ResourceManager.GetString("MaterialProperties_Thickness", resourceCulture);
            }
        }
    }
}
