//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomagConnect.IntelliDivide.Contracts.Statistics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatisticsDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatisticsDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomagConnect.IntelliDivide.Contracts.Statistics.StatisticsDisplayNames", typeof(StatisticsDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattenverbrauch (Fläche).
        /// </summary>
        public static string BoardsUsedArea {
            get {
                return ResourceManager.GetString("BoardsUsedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattenverbrauch (Anzahl).
        /// </summary>
        public static string BoardsUsedQuantity {
            get {
                return ResourceManager.GetString("BoardsUsedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten.
        /// </summary>
        public static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kantencode.
        /// </summary>
        public static string EdgebandCode {
            get {
                return ResourceManager.GetString("EdgebandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbrauchte Länge.
        /// </summary>
        public static string LengthUsed {
            get {
                return ResourceManager.GetString("LengthUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinenname.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialcode.
        /// </summary>
        public static string MaterialCode {
            get {
                return ResourceManager.GetString("MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restezuwachs (Fläche).
        /// </summary>
        public static string OffcutsGrowthArea {
            get {
                return ResourceManager.GetString("OffcutsGrowthArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restezuwachs (Anzahl).
        /// </summary>
        public static string OffcutsGrowthQuantity {
            get {
                return ResourceManager.GetString("OffcutsGrowthQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produzierte Reste (Fläche).
        /// </summary>
        public static string OffcutsProducedArea {
            get {
                return ResourceManager.GetString("OffcutsProducedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produzierte Reste (Anzahl).
        /// </summary>
        public static string OffcutsProducedQuantity {
            get {
                return ResourceManager.GetString("OffcutsProducedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resteverbrauch (Fläche).
        /// </summary>
        public static string OffcutsUsedArea {
            get {
                return ResourceManager.GetString("OffcutsUsedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resteverbrauch (Anzahl).
        /// </summary>
        public static string OffcutsUsedQuantity {
            get {
                return ResourceManager.GetString("OffcutsUsedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimierungs-Id.
        /// </summary>
        public static string OptimizationId {
            get {
                return ResourceManager.GetString("OptimizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimierungsname.
        /// </summary>
        public static string OptimizationName {
            get {
                return ResourceManager.GetString("OptimizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teile (Fläche).
        /// </summary>
        public static string PartsArea {
            get {
                return ResourceManager.GetString("PartsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teile (Anzahl).
        /// </summary>
        public static string PartsQuantity {
            get {
                return ResourceManager.GetString("PartsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übertragene Teile (Anzahl).
        /// </summary>
        public static string PartsTransferredQuantity {
            get {
                return ResourceManager.GetString("PartsTransferredQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionszeit.
        /// </summary>
        public static string ProductionTime {
            get {
                return ResourceManager.GetString("ProductionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtkosten.
        /// </summary>
        public static string TotalCosts {
            get {
                return ResourceManager.GetString("TotalCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übertragen am.
        /// </summary>
        public static string TransferredAt {
            get {
                return ResourceManager.GetString("TransferredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übertragen von.
        /// </summary>
        public static string TransferredBy {
            get {
                return ResourceManager.GetString("TransferredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschnitt (Fläche).
        /// </summary>
        public static string WasteArea {
            get {
                return ResourceManager.GetString("WasteArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschnitt (%).
        /// </summary>
        public static string WastePercentage {
            get {
                return ResourceManager.GetString("WastePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
